const applicationTitles = {
	orderNumber: 'Номер заказа',
	operationType: 'Тип операции',
	customerName: 'ФИО покупателя',
	docType: 'Тип документа',
	passportNumSerial: 'Номер и серия',
	passportReceiveDate: 'Дата выдачи',
	passportIssuedBy: 'Кем выдан',
	returnGoods: 'Товары к возврату',
	count: 'Кол-во',
	lotNumber: 'Номер партии товара',
	returnCause: 'Причина возврата',
	goodState: 'Сосотояние товара',
	checkNumber: 'Номер чека',
	purchaseDate: 'Дата покупки',
	purchasePlace: 'Место покупки',
	returnSum: 'Сумма к возврату',
	paymentMethod: 'Способ оплаты покупки',
	accountHolderName: 'ФИО Владельца счета',
	bankName: 'Наименование банка',
	bic: 'БИК',
	correspondentAccount: 'Корреспондентский счет',
	transactionAccount: 'Расчетный счет',
	exchangeGoods: 'Товары к обмену',
	exchangeCause: 'Причина обмена',
	forWhatExchange: 'На что обмен',
	howExchange: 'Как обменять',
	exchangeDate: 'Дата',
	exchangeTime: 'Примерное время',
	deliveryAddress: 'Адрес доставки',
	exchangeAddress: 'Адрес обмена',
}


export default applicationTitles
